### ISSUE TITLE
Custom yaml loader to support include mechanism

### ISSUE THREAD

**Issue by ksiero** [jbeder/yaml-cpp#1001]
Hi, is there any plan in the future to support custom yaml loaders? I need include mechanism, to be able to split one big yaml document into several smaller ones. The syntax would look like the one in `pyyaml-include`:
```yaml
file1: !include 1.yml
file2: !include 2.yml
```
see: https://github.com/tanbro/pyyaml-include

Right know there is no other way to support that different than a wrapper class that would check tag of all nodes and include a document.

Related to above request is also support to access a filename (if document was parsed from a file). This could be just a shared pointer in the Node object that holds a string. This would make possible to indicate where Node is (filename and line number).

**Comment by fha-dev** [comment]
I would also love to see something like that, since we had to implement this functionality via a dedicated external tool.

It is also valuable to have the ability to select only some nodes of the included file at specific points, selectable via "Node path".
For example:

File1 (included):
 
Node1: 
    Key1: Value1
    Key2: Value2

File2 (includes parts of file 1):

!include File1: [ Node1, Key1 ]

Would lead to the result:

Node1:
   Key1: Value1

**Comment by jbeder** [comment]
No, but you can probably write a wrapper function that does that.
