### ISSUE TITLE
Segfault with _GLIBCXX_DEBUG defined

### ISSUE THREAD

**Issue by joejustesen** [jbeder/yaml-cpp#1080]
You can also cause a segfault by defining D_GLIBCXX_DEBUG when building the unit tests and running them.

**Comment by alex-thiessen-for-siemens** [comment]
Could it be because

> you can only link code compiled with debug mode and code compiled without debug mode if no instantiation of a container is passed between the two translation units.

, yet `yaml-cpp` **mixes** header-implemented code (affected by the `_GLIBCXX_DEBUG` flag on user side) with library (linked) code (unaffected by the `_GLIBCXX_DEBUG` flag on user side)?

https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html#debug_mode.using.mode

If that the case, then it's not a bug.

**Comment by alex-thiessen-for-siemens** [comment]
To my knowledge, segfaults you observed are due to build issues in versions ≤0.6.3.

From now on, `yaml-cpp` is proven to be `_GLIBCXX_DEBUG`-compatible (even with pedantic checks for implementation-defined behavior) as part of PR checks.
