### ISSUE TITLE
Provide cmake file FindYamlCpp05 that asserts the API version

### ISSUE THREAD

**Issue by jwuttke** [jbeder/yaml-cpp#336]
Jesse, would you be willing to maintain the following FindYamlCpp05.make? Or where else should I submit it? Let me take the occasion to thank you for your work on yaml-cpp - Joachim

```
# Locate yaml-cpp with API version 0.5
#
# This module defines
# YAMLCPP_FOUND, if false, do not try to link to yaml-cpp
# YAMLCPP_LIBRARY, where to find yaml-cpp
# YAMLCPP_INCLUDE_DIR, where to find yaml.h
#
# By default, the dynamic libraries of yaml-cpp will be found. To find the static ones instead,
# you must set the YAMLCPP_STATIC_LIBRARY variable to TRUE before calling find_package(YamlCpp ...).
#
# If yaml-cpp is not installed in a standard path, you can use the YAMLCPP_DIR CMake variable
# to tell CMake where yaml-cpp is.

include (CheckCppIncludeFile)
include (CheckCXXSourceRuns)

# find the yaml-cpp include directory
find_path(YAMLCPP_INCLUDE_DIR yaml-cpp/yaml.h
    PATH_SUFFIXES include
    PATHS
    ~/Library/Frameworks/yaml-cpp/include/
    /Library/Frameworks/yaml-cpp/include/
    /usr/local/include/yaml-cpp/
    /usr/local/include/
    /usr/include/yaml-cpp/
    /usr/include/
    /sw/yaml-cpp/ # Fink
    /opt/local/yaml-cpp/ # DarwinPorts
    /opt/csw/yaml-cpp/ # Blastwave
    /opt/yaml-cpp/
    ${YAMLCPP_DIR}/include/)

set(CMAKE_REQUIRED_INCLUDES ${YAMLCPP_INCLUDE_DIR})
set(CMAKE_REQUIRED_QUIET True)

# first look for outdated yaml-cpp0.3 include files
unset(YAMLCPP_FOUND_03 CACHE)
check_include_file("yaml-cpp/aliasmanager.h" YAMLCPP_FOUND_03)
if(${YAMLCPP_FOUND_03})
    message(WARNING "Found include file for libyaml-cpp0.3. Most probably this precludes libyaml-cpp0.5 from being properly installed")
endif()

# now look for needed yaml-cpp0.5 include files
unset(YAMLCPP_FOUND_05 CACHE)
check_include_file("yaml-cpp/node/detail/iterator_fwd.h" YAMLCPP_FOUND_05)
if(${YAMLCPP_FOUND_05})
else()
    message(FATAL_ERROR "Include file for libyaml-cpp0.5 not found")
endif()

# attempt to find static library first if this is set
if(YAMLCPP_STATIC_LIBRARY)
    set(YAMLCPP_STATIC libyaml-cpp.a)
endif()

# find the yaml-cpp library
find_library(YAMLCPP_LIBRARY
    NAMES ${YAMLCPP_STATIC} yaml-cpp
    PATH_SUFFIXES lib64 lib
    PATHS ~/Library/Frameworks
    /Library/Frameworks
    /usr/local
    /usr
    /sw
    /opt/local
    /opt/csw
    /opt
    ${YAMLCPP_DIR}/lib)

# try to compile, link, and run a test program
unset(YAMLCPP_RUNS CACHE)
set(CMAKE_REQUIRED_LIBRARIES yaml-cpp)
check_cxx_source_runs("#include \"yaml-cpp/yaml.h\"\n#include <assert.h>\nint main() {\n    YAML::Node node = YAML::Load(\"[1, 2, 3]\");\n    assert(node.IsSequence());\n}" YAMLCPP_RUNS)
if(${YAMLCPP_RUNS})
else()
    message(FATAL_ERROR "Test of libyaml-cpp0.5 failed")
endif()

# handle the QUIETLY and REQUIRED arguments and set YAMLCPP_FOUND to TRUE if all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(YAMLCPP DEFAULT_MSG YAMLCPP_INCLUDE_DIR YAMLCPP_LIBRARY)
mark_as_advanced(YAMLCPP_INCLUDE_DIR YAMLCPP_LIBRARY)
```

**Comment by jbeder** [comment]
I've never been sure what the point of these FindXXX files is. Where would this go, say, if it were Boost? It doesn't look like Boost packages a similar looking file.

**Comment by riemancon** [comment]
Answering the questions/comments in more or less reverse order, the nominal place for cmake FindXXX modules is /usr/local/share/cmake/Modules.  There are ~150 that are bundled with cmake, FindBoost.cmake is one of them.

The point is so that user written cmake files can be more easily maintained.  One simply adds a line like 'find_package(YamlCpp REQUIRED)' and then cmake does all the work of finding the actual package, typically this means setting include and library cmake variables.  It's basically an analog of the pkg_config mechanism but for cmake.  Cmake will look in /usr/local/share/cmake/Modules for the FindXXX.cmake file by default.  The user can specify extra locations using the CMAKE_MODULE_PATH.  So for yaml-cpp I would either put FindYamlCpp.cmake in the default location (if it were writable/accessible to me) or I would put it in a project location and add the path via the aforementioned cmake variable.

I would hope that the yaml-cpp would provided a cmake FindXXX module, it makes writing and maintaining cmake projects considerably simpler.  Well written FindXXX modules included capability to do version checks and distinguish between mutually exclusive options like single/multithreaded and static/dynamic linking. 

Hope this helps.

**Comment by Qix-** [comment]
Shouldn't it be _FindYamlCpp05.**c**make_?

Also, you should submit it as a pull request :+1: that is the proper way to put forth a file for review. This would be nice to have.

**Comment by paulnovo** [comment]
You don't need to write FindProject.cmake files to look for projects that are CMake projects, like this one. That is _if_ the project correctly installs a project-config.cmake and project-version.cmake file. Which yaml-cpp does not, and is my fault actually. When I sent the patch to create these files, I didn't add it to the cmake install. This is related to #127. I'll put together a pull request to address this.

**Comment by flv0** [comment]
As noted in #347 I was just hitting this problem. I can confirm that with this patch the yaml-cpp-config.cmake and the other files are being installed properly, and by setting CMAKE_PREFIX_PATH and using find_package(yaml-cpp) my application finds and successfully compiles/links against the deployed version.
