### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by tatraian** [jbeder/yaml-cpp#415]
Hello,

I just want to ask that do you plan to release new version without boost dependency? If yes when?

**Comment by tatraian** [comment]
Hello,

Any progress? Please release a new version. I would like to add it to hunter C++ package manager (https://github.com/ruslo/hunter)

**Comment by nerzhul** [comment]
can we have a new release, yaml-cpp is a great library, but we need C++11 support without boost, boost doesn't compile on FreeBSD + Raspberry PI

**Comment by jkhoogland** [comment]
when is this going to happen ??
it is over a year since a last release.

**Comment by bvrabete** [comment]
Same here.

**Comment by just6979** [comment]
Commits are in to replace boost with C++11.

Why don't you guys pull the master branch and do some testing on it to help out?

**Comment by ibaned** [comment]
The master branch works great for me after I contributed some warning fixes.
Any ETA for the next official release ?

**Comment by lxmota** [comment]
Any ETA for an official release?

**Comment by nerzhul** [comment]
It's anoying to see many users and great libraries uses it but author seems to be absent :(

**Comment by vks** [comment]
@nerzhul You sound very entitled for a user of a free library. If you really cared, you could offer to help the author or just fork the library and make a new release.

**Comment by jbeder** [comment]
Hi, I'm here! I'll get a release out soon, hopefully...

**Comment by nerzhul** [comment]
Nice, please tell me, i will send a FreeBSD port patch and ensure Archlinux correctly dropped the boost library in deps

**Comment by Zerophase** [comment]
What's needed for the next release?

**Comment by mwoehlke-kitware** [comment]
*Please* fix #539 before making a release. Packagers, for one, will be grateful.

**Comment by breznak** [comment]
@jbeder Could you please state when will be the next release? 
Many projects use your code, and a number of the open issues ( #502 #525 #523 etc) are caused because people use the stable release, and not custom built master-branch. 
Or is there a specific reason holding you off making the release? 

Also, please consider if you would like to add some of the active contributors here as "another manager" to the repo. As I see this too much recently, many great libraries suffer, as the original author moves on (interest, job, life...) but people still want to use the "original" library, but there is no active management.

**Comment by jbeder** [comment]
Just released [yaml-cpp-0.6.0](https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.6.0)
