### ISSUE TITLE
parse string value null fail

### ISSUE THREAD

**Issue by jingshaoqi** [jbeder/yaml-cpp#590]
I have test.yaml contents follow:
port: 1234
server: null

but parse server fail:
std::string str = node["server"].as<<std::string>>();

yaml-cpp: error at line 0, column 0: bad conversion
if change null to other, it's ok

**Comment by kcollinssibley** [comment]
I have also run into this issue on yaml-cpp-0.6.2.
This snippet of a yaml log file was generated using yaml-cpp-0.5.3:
```yaml
...
inventory:
  type: NULL
  value: ~
...
```
When upgrading my system to use yaml-cpp-0.6.2, I get the same error when trying to parse the log file created using yaml-cpp-0.5.3:
```
terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  yaml-cpp: error at line 2, column 9: bad conversion
Aborted (core dumped)
```

If I regenerate the file using yaml-cpp-0.6.2, the null value is handled differently:
```yaml
...
inventory:
  type: "NULL"
  value: ~
...
```

It is not feasible for us to regenerate all of our yaml files previously generated using yaml-cpp-0.5.3. This bug is preventing us from updating yaml-cpp and using new features elsewhere in out system.

**Comment by jbeder** [comment]
Reasonable. If you want to submit a PR that allows parsing null as a string, happy to review it.

**Comment by HensonLi** [comment]
@jbeder  Is there any PR or ticket relevant to how to parse a node with a null key
just like : 
a:
   b:1
     :2
   c:3

**Comment by jbeder** [comment]
@HensonLi a null key is like any other key. Please ask usage questions like this on Stack Overflow.

**Comment by HensonLi** [comment]
Got it， thanks for your reply, will post the issue onto Stack Overflow
later!


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
19/03/01
上午9:12:14

Jesse Beder <notifications@github.com> 于2019年3月1日周五 上午12:36写道：

**Comment by dota17** [comment]
@jingshaoqi 
I have finish this feature and add the support to null type for `as<std::string>`. `as<std::string>` outputs the `"null"` for null type node. This can be changed as `"~"`, `"Null"`, etc.
