### ISSUE TITLE
Add Namespace to your target

### ISSUE THREAD

**Issue by atar-axis** [jbeder/yaml-cpp#661]
Nearly two years ago you merged a [pull request](https://github.com/jbeder/yaml-cpp/pull/344) which added some support for *more modern* CMake.
A step toward the right direction I think, but unfortunately the CMake code now includes variables like `YAML_CPP_LIBRARIES` which leads to spaghetti code somehow...

It would be beneficial if you would export your targets instead, this is considered **best practice**, is there any good reason why you don't do it yet? If not, I can try to come up with a patch.

Have a look at https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/#good-boys-export-their-targets

If ready, one could import the library and all necessary includes, flags,... via

```
find_package(yaml-cpp 0.6.0 REQUIRED)

target_link_libraries(${PROJECT_NAME}
    PRIVATE
        yaml-cpp::yaml-cpp
)
```

**Comment by stotko** [comment]
This is supported since #583 has been merged. The only thing missing is the alias target, so at the moment, this will work:

```
# Note: The tagged 0.6.2 version does not include #583, so you need the version from master
find_package(yaml-cpp 0.6.2 REQUIRED)

target_link_libraries(${PROJECT_NAME} PRIVATE yaml-cpp)
```

There has been some work regarding modernizing and cleaning the CMake script including bumping the required CMake version to 3.1. So adding support for alias targets should not be a problem.

**Comment by gocarlos** [comment]
this was done already in cmake though the namespaced name is different than the project name.

As most of the cmake projects use `PROJECT_NAME::TARGET_NAME` we should imho change the the namespace name to `yaml-cpp::yaml-cpp` instead of `yaml::yaml`

e.g. downstream package managers expect the default behaviour and have issues then https://github.com/conan-io/conan-center-index/issues/405
