### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by offa** [jbeder/yaml-cpp#967]
Please consider a new release, the last one was a year ago. :smiley:

**Comment by offa** [comment]
ping @jbeder

**Comment by SupervisedThinking** [comment]
well even thid party stuff nags about a new release:
https://github.com/PCSX2/pcsx2/blob/master/cmake/SearchForStuff.cmake#L278-L279

**Comment by townsend2010** [comment]
Please?

**Comment by blsqr** [comment]
There's no GitHub activity from @jbeder since January – does anyone know if he's ok?

**Comment by emastrom** [comment]
@jbeder looking forward to using yaml-cpp in my project. There are bug fixes and warnings clean up that occurred on master.  Is there a ballpark time for release or any help required to perform one?

**Comment by allanleal** [comment]
Please, create a new release so that the conda-forge package `yaml-cpp` (https://anaconda.org/conda-forge/yaml-cpp) is updated with the most current version of `master`. Just run across a bug that is fixed in master but not in 0.63 (current release). The bug has to do with `NAN` not been encoded as `.nan` (it gets encoded as `nan` in 0.63, and correctly as `.nan` in master).

**Comment by jbeder** [comment]
Done, released 0.7.0.
